### ISSUE TITLE
Plot from examples does not appear in obsidian on macOS

### ISSUE THREAD

**Issue by Ncit** [Some-Regular-Person/obsidian-vega#2]
I put plot below into obsidian note and nothing happened. Only signals appear
https://vega.github.io/editor/#/examples/vega/tree-layout
<img width="1190" alt="Screenshot 2023-05-03 at 17 46 57" src="https://user-images.githubusercontent.com/2179841/235951963-7cc525af-d3eb-4935-bfaf-50b509e768c6.png">

**Comment by Justin-J-K** [comment]
I was not able to replicate your issue. Is it possible that the "data/flare.json" file was missing from your Obsidian vault directory?

**Comment by Ncit** [comment]
I simply put json text into file from link https://vega.github.io/editor/#/examples/vega/tree-layout.  And after editing I receive result like on screenshot above
<img width="913" alt="Screenshot 2023-05-05 at 14 04 28" src="https://user-images.githubusercontent.com/2179841/236441747-a7d00c8e-6e84-4ca7-99cc-be6c6ce4c8b8.png">

**Comment by Justin-J-K** [comment]
Please make sure you have the "data/flare.json" file.

**Comment by Ncit** [comment]
thank you, I found issue that file requested inside json but missing in folder.
